services:
  mysql:
    image: mysql:8.0
    container_name: mysql_almasdb
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./backend/.env
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - almas_network

  backend:
    build: ./backend
    container_name: almas_backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DJANGO_SETTINGS_MODULE: backend.settings
    depends_on:
      - mysql
    ports:
      - "6220:8000" # Django Gunicorn exposed at 6220
    volumes:
      - ./backend:/app
      - media_data:/app/media
    networks:
      - almas_network

  dashboard:
    build: ./dashboard
    container_name: almas_frontend
    restart: always
    ports:
      - "6221:80" # Frontend served via Nginx at 6221
    networks:
      - almas_network

networks:
  almas_network:
    driver: bridge

volumes:
  mysql_data:
  media_data:
